DrawTime: 5
UseTimeDraw: false
TimeDrawCheckIntervalSeconds: 60
TimeDraws:
- 00:00:00
- 06:00:00
- '12:00:00'
- '18:00:00'
GlobalBoughtMessage: true
TicketCost: 1000.0
MoneyToPot: 1500.0
ExtraInPot: 0.0
Refund: 1000.0
TaxesPercent: 0
ServerAccount: rolemine
MinPlayers: 1
BuyCooldownTimeSeconds: 10
EnableChanceNoWin: true
ChanceNoWinIfLessTicketsSold: true
ChanceNoWinPercent: 150/200
NoWinBackToPotPercent: 100
Reminder: true
RemindIntervalSeconds: 60
OnlyOnlineWin: false
LoginWinMessage: true
LoginWinMessageDelayTicks: 10
PerformCommandOnLotteryCMD: false
CommandOnLotteryCMD: lottery status
UpdateCheck: true
Metrics: true
TicketLimits:
  Default: 1000
BlockedWorlds:
- testworld
WinCommands:
  Enabled: false
  ExecuteIfOffline: false
  Commands:
  - xp 10l %player%
